"""Strip metadata from files uploaded before the pipeline started doing it (SPEC §9).

    uv run python -m app.cli.strip_media_metadata --dry-run   # count what would change
    uv run python -m app.cli.strip_media_metadata             # rewrite them

Uploads are cleaned on the way into the bucket now, but everything stored before
that still carries whatever the camera wrote — which for a phone photo means the
coordinates it was taken at. The code fix does nothing for those files; this is
what makes the existing library safe, and it is a one-off.

Every object is re-read, stripped, and written back **under its own key**, so no
URL changes and no database row has to be touched. `strip_metadata` returns its
input unchanged when there is nothing to remove, which is what makes a re-run
free and makes `--dry-run` honest: a file is only rewritten when the bytes
actually differ.

Thumbnails are skipped deliberately. They are generated by `render_thumbnail`,
which has always dropped metadata as a side effect of converting to RGB — the
derived files were never the problem.
"""

from __future__ import annotations

import argparse
import asyncio
import sys

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import SessionLocal, engine
from app.models.review import ReviewMedia
from app.models.user import User
from app.services import storage
from app.services.media import strip_metadata


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="strip-media-metadata", description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what carries metadata without writing anything back.",
    )
    return parser.parse_args(argv)


async def _clean_one(url: str | None, *, dry_run: bool) -> bool:
    """Rewrite one stored object in place. True when it actually carried metadata.

    Failures are logged and swallowed rather than raised: one unreadable object
    from a half-finished upload should not stop the sweep before it reaches the
    rest of the library.
    """
    key = storage.key_for_url(url)
    if key is None:
        return False

    try:
        data = await storage.get_object(key)
    # Broad on purpose: one unreadable object — a half-finished upload, a row
    # pointing at something since deleted — must not stop the sweep before it
    # reaches the rest of the library.
    except Exception as exc:
        print(f"  ! could not read {key}: {exc}")
        return False

    content_type = storage.detect_content_type(data)
    if content_type is None:
        return False

    try:
        clean = await asyncio.to_thread(strip_metadata, data, content_type)
    except Exception as exc:  # as above
        print(f"  ! could not strip {key}: {exc}")
        return False

    if clean == data:
        return False

    if not dry_run:
        await storage.put_object(key, clean, content_type)
    return True


async def _sweep(session: AsyncSession, *, dry_run: bool) -> tuple[int, int]:
    """Walk every stored original. Returns (rewritten, inspected)."""
    media_urls = (await session.execute(sa.select(ReviewMedia.url))).scalars().all()
    avatar_urls = (
        (await session.execute(sa.select(User.avatar_url).where(User.avatar_url.is_not(None))))
        .scalars()
        .all()
    )

    urls = [*media_urls, *avatar_urls]
    rewritten = 0
    for url in urls:
        if await _clean_one(url, dry_run=dry_run):
            rewritten += 1

    return rewritten, len(urls)


async def _run(*, dry_run: bool) -> int:
    try:
        async with SessionLocal() as session:
            rewritten, inspected = await _sweep(session, dry_run=dry_run)
    finally:
        await engine.dispose()

    verb = "would rewrite" if dry_run else "rewrote"
    print(f"strip-media-metadata: inspected {inspected} object(s), {verb} {rewritten}")
    if dry_run and rewritten:
        print("Run again without --dry-run to strip them.")
    return 0


def main(argv: list[str]) -> int:
    args = _parse_args(argv)
    return asyncio.run(_run(dry_run=args.dry_run))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
