"""initial schema

Revision ID: 0a3d28fae88c
Revises: 
Create Date: 2026-08-01 14:55:44.016110

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0a3d28fae88c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('external_id', name=op.f('uq_games_external_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_games_slug'))
    )
    op.create_index(op.f('ix_games_title'), 'games', ['title'], unique=False)
    op.create_table('genres',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_genres_slug'))
    )
    op.create_table('platforms',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('name', name=op.f('uq_platforms_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_platforms_slug'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(username) >= 3', name=op.f('ck_users_username_min_length')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_is_lowercase')),
    sa.CheckConstraint('username = lower(username)', name=op.f('ck_users_username_is_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('backlog_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TO_BE_PLAYED', 'PLAYING', 'COMPLETED', 'DROPPED', name='backlog_status'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_backlog_items_position_non_negative')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_backlog_items_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backlog_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backlog_items')),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_backlog_items_user_id_game_id')
    )
    op.create_index('ix_backlog_items_user_id_status_position', 'backlog_items', ['user_id', 'status', 'position'], unique=False)
    op.create_table('favorite_games',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_favorite_games_position_non_negative')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_favorite_games_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_games_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'game_id', name=op.f('pk_favorite_games'))
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('followee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='follow_status'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name=op.f('ck_follows_no_self_follow')),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name=op.f('fk_follows_followee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id', name=op.f('pk_follows'))
    )
    op.create_index('ix_follows_followee_id_status', 'follows', ['followee_id', 'status'], unique=False)
    op.create_index('ix_follows_follower_id_status', 'follows', ['follower_id', 'status'], unique=False)
    op.create_table('game_genres',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_genres_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_game_genres_genre_id_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id', name=op.f('pk_game_genres'))
    )
    op.create_table('game_platforms',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_platforms_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_game_platforms_platform_id_platforms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'platform_id', name=op.f('pk_game_platforms'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_text', sa.String(length=5000), nullable=True),
    sa.Column('playtime_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('playtime_minutes IS NULL OR playtime_minutes >= 0', name=op.f('ck_reviews_playtime_non_negative')),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name=op.f('ck_reviews_rating_in_range')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_reviews_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_reviews_user_id_game_id')
    )
    op.create_index('ix_reviews_game_id_created_at', 'reviews', ['game_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_reviews_user_id_created_at', 'reviews', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('trending_scores',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_trending_scores_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'window', name=op.f('pk_trending_scores'))
    )
    op.create_index('ix_trending_scores_window_score', 'trending_scores', ['window', sa.literal_column('score DESC')], unique=False)
    op.create_table('comments',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(text) BETWEEN 1 AND 500', name=op.f('ck_comments_text_length')),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('fk_comments_parent_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_comments_review_id_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_review_id_created_at', 'comments', ['review_id', 'created_at'], unique=False)
    op.create_table('likes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_likes_review_id_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'review_id', name=op.f('pk_likes'))
    )
    op.create_index('ix_likes_review_id_created_at', 'likes', ['review_id', 'created_at'], unique=False)
    op.create_table('review_media',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='media_type'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='processing_status'), server_default='PENDING', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0 AND position < 10', name=op.f('ck_review_media_position_in_range')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_media_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_media')),
    sa.UniqueConstraint('review_id', 'position', name='uq_review_media_review_id_position')
    )
    op.create_index(op.f('ix_review_media_review_id'), 'review_media', ['review_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('NEW_FOLLOWER', 'FOLLOW_REQUEST', 'FOLLOW_REQUEST_APPROVED', 'REVIEW_LIKED', 'REVIEW_COMMENTED', 'COMMENT_REPLIED', 'BACKLOG_GAME_REVIEWED', name='notification_type'), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('comment_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_notifications_actor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_notifications_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_notifications_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_recipient_id_created_at', 'notifications', ['recipient_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_recipient_id_unread', 'notifications', ['recipient_id'], unique=False, postgresql_where=sa.text('is_read = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_recipient_id_unread', table_name='notifications', postgresql_where=sa.text('is_read = false'))
    op.drop_index('ix_notifications_recipient_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_review_media_review_id'), table_name='review_media')
    op.drop_table('review_media')
    op.drop_index('ix_likes_review_id_created_at', table_name='likes')
    op.drop_table('likes')
    op.drop_index('ix_comments_review_id_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_trending_scores_window_score', table_name='trending_scores')
    op.drop_table('trending_scores')
    op.drop_index('ix_reviews_user_id_created_at', table_name='reviews')
    op.drop_index('ix_reviews_game_id_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('game_platforms')
    op.drop_table('game_genres')
    op.drop_index('ix_follows_follower_id_status', table_name='follows')
    op.drop_index('ix_follows_followee_id_status', table_name='follows')
    op.drop_table('follows')
    op.drop_table('favorite_games')
    op.drop_index('ix_backlog_items_user_id_status_position', table_name='backlog_items')
    op.drop_table('backlog_items')
    op.drop_table('users')
    op.drop_table('platforms')
    op.drop_table('genres')
    op.drop_index(op.f('ix_games_title'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###

    # Autogenerate does not clean up the enum types that CREATE TABLE created
    # implicitly; without this a downgrade/upgrade cycle fails on DuplicateObject.
    for enum_name in (
        "backlog_status",
        "follow_status",
        "media_type",
        "notification_type",
        "processing_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
