"""add trigram search indexes

Revision ID: de134620f0fc
Revises: 0a3d28fae88c
Create Date: 2026-08-02 00:00:04.444817

Search (SPEC §6.6) matches substrings, which the plain btree indexes cannot
serve, and ranks by pg_trgm's similarity(). Both need the pg_trgm extension, so
it is created here rather than assumed — the test database drops and rebuilds
the public schema, which takes the extension with it.

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "de134620f0fc"
down_revision: str | None = "0a3d28fae88c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Not autogenerated: extensions are not part of the model metadata, but both
    # the indexes below and the similarity() ranking depend on this one.
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_games_title_trgm",
        "games",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_users_display_name_trgm",
        "users",
        ["display_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_users_username_trgm",
        "users",
        ["username"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # pg_trgm is deliberately left installed: it is a shared database object that
    # something else may since have started using, and re-creating it is free.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_users_username_trgm",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_users_display_name_trgm",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_games_title_trgm",
        table_name="games",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
